module.exports = {
  apps: [
    {
      name: "boss-ai-api-gateway",
      script: "dist/index.js",
      cwd: "/var/www/boss-ai/backend/main",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        DB_PATH: "/var/www/boss-ai/backend/ozon-manager/data/ozon_manager.db",
        LOG_LEVEL: "info",
        LOG_FILE: "./backend/logs/api_gateway.log",
        CORS_ORIGIN: "https://boss-ai.online",
        RATE_LIMIT_WINDOW_MS: "900000",
        RATE_LIMIT_MAX_REQUESTS: "100",
        OZON_MANAGER_URL: "http://localhost:4200",
        AI_SERVICES_URL: "http://localhost:4300",
        ANALYTICS_SERVICE_URL: "http://localhost:4400",
        TELEGRAM_BOT_TOKEN: "8412679381:AAHYp7dXkpvXusiZc4zzLQ_d0L3lf-AfuNs",
        JWT_SECRET: "boss-ai-super-secret-jwt-key-2024-production-v1",
        JWT_EXPIRES_IN: "30d",
      },
      error_file: "./backend/logs/api_gateway_err.log",
      out_file: "./backend/logs/api_gateway_out.log",
      log_file: "./backend/logs/api_gateway_combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      node_args: "--max-old-space-size=1024",
    },
    {
      name: "boss-ai-ozon-manager",
      script: "dist/index.js",
      cwd: "/var/www/boss-ai/backend/ozon-manager",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 4200,
        DB_PATH: "/var/www/boss-ai/backend/ozon-manager/data/ozon_manager.db",
        LOG_LEVEL: "info",
        LOG_FILE: "./backend/logs/ozon_manager.log",
        CORS_ORIGIN: "https://boss-ai.online",
        OZON_API_BASE_URL: "https://api-seller.ozon.ru",
        OZON_API_TIMEOUT: 30000,
        OZON_API_RATE_LIMIT: 50,
        SCHEDULER_ENABLED: "true",
        SCHEDULER_TIMEZONE: "Europe/Moscow",
      },
      env_file: "/var/www/boss-ai/.env",
      env_production: {
        NODE_ENV: "production",
        PORT: 4200,
      },
      error_file: "./backend/logs/ozon_manager_err.log",
      out_file: "./backend/logs/ozon_manager_out.log",
      log_file: "./backend/logs/ozon_manager_combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      node_args: "--max-old-space-size=1024",
    },
    {
      name: "boss-ai-analytics-service",
      script: "dist/index.js",
      cwd: "/var/www/boss-ai/backend/analytics-service",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 4400,
        DB_PATH: "/var/www/boss-ai/data/boss_ai.db",
        LOG_LEVEL: "info",
        CORS_ORIGIN: "https://boss-ai.online",
        JWT_SECRET: "boss-ai-super-secret-jwt-key-2024-production-v1",
      },
      error_file: "./backend/logs/analytics_service_err.log",
      out_file: "./backend/logs/analytics_service_out.log",
      log_file: "./backend/logs/analytics_service_combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      node_args: "--max-old-space-size=512",
    },
  ],
};
